package com.mycompany.javaassignment.UI;

import java.io.*;
import com.mycompany.javaassignment.Class.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class InventoryUI extends javax.swing.JFrame {

//    InventoryUI inventoryUI = new InventoryUI();
    DefaultTableModel model = new DefaultTableModel();
    private String[] colname = {"Item No", "Item Name", "Item Available", "Item In Progress", "Total Quantity"};
    Inventory inventory = new Inventory();

    private static final String STOCK_MOVEMENT_LOG_FILENAME = System.getProperty("user.dir") + "/src/main/java/com/mycompany/javaassignment/Database/stockMovementLog.txt";
    private static final String INVENTORY_FILENAME = System.getProperty("user.dir") + "/src/main/java/com/mycompany/javaassignment/Database/inventory.txt";

    public InventoryUI() {
        model.setColumnIdentifiers(colname);
        initComponents();

        tableUI();

        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);

        jTextField1.setFocusable(false);
        jTextField2.setFocusable(false);
        jTextField4.setFocusable(false);
        jTextField5.setFocusable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("NEXUS SDN BHD POTS");

        jTable1.setModel(model);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton4.setText("EDIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Total Quantity");

        jLabel4.setText("Available Item");

        jLabel5.setText("Item In Progress");

        jLabel2.setText("Item ID");

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setText("Item Name");

        jLabel7.setText("Reason");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Out of Stock", "Insufficient Stock", "Scheduled Re-stock", "Others" }));

        jLabel9.setText("Description");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(104, 104, 104)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(104, 104, 104)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jTextField3))
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel8)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox2, jLabel3, jLabel4, jTextField1, jTextField2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow >= 0) {
            jTextField1.setText(String.valueOf(model.getValueAt(selectedRow, 0))); // Item No
            jTextField2.setText(String.valueOf(model.getValueAt(selectedRow, 1))); // Item Name            
            jSpinner1.setValue(Integer.parseInt(String.valueOf(model.getValueAt(selectedRow, 2)))); // Available Item
            jTextField4.setText(String.valueOf(model.getValueAt(selectedRow, 3))); // Item In Progress            
            jTextField5.setText(String.valueOf(model.getValueAt(selectedRow, 4))); // Total Quantity            
        } else {
            JOptionPane.showMessageDialog(null, "No row selected.");
        }
    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            String itemNo = jTextField1.getText();
            String itemName = jTextField2.getText();
            String reason = String.valueOf(jComboBox2.getSelectedItem());
            String description = jTextField3.getText();
            int qtyInProcess = Integer.parseInt(jTextField5.getText());
            int newQtyAvailable = (int) jSpinner1.getValue();
            int newTotalQty = qtyInProcess + newQtyAvailable;

            if (itemNo.isEmpty() || itemName.isEmpty() || reason.isEmpty() || description.isEmpty() || newQtyAvailable < 0) {
                JOptionPane.showMessageDialog(null, "Invalid data.");
            } else {
                // Confirmation dialog for editing reason and description
                if (JOptionPane.showConfirmDialog(this, "Are you sure you want to edit the reason and description?",
                        "Edit Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    inventory.editStock(itemNo, itemName, reason, description, newTotalQty, qtyInProcess, newQtyAvailable);

                    model.setValueAt(itemNo, selectedRow, 0);           // Update Item ID
                    model.setValueAt(itemName, selectedRow, 1);         // Update Item Name
                    model.setValueAt(newQtyAvailable, selectedRow, 2);  // Update Available Quantity
                    model.setValueAt(qtyInProcess, selectedRow, 3);  // Update Quantity in Progress
                    model.setValueAt(newTotalQty, selectedRow, 4);      // Update Total Quantity  
                    
                    clearFormFields();
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to edit.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
//       inventoryUI.setVisible(true);
        new InventoryManagerUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    private void tableUI() {
        model.setRowCount(0); // Clear the table before populating it

        try (BufferedReader br = new BufferedReader(new FileReader(INVENTORY_FILENAME))) {
            String line;

            while ((line = br.readLine()) != null) {
                String[] data = line.split(", "); // Assuming the file is comma-separated

                if (data.length >= 5) { // Ensure there are enough fields (7 columns)
                    String itemNo = data[0];
                    String itemName = data[1];
                    String totalQty = data[2];
                    String inProgress = data[4];
                    String available = data[3];
//                String reason = data[5];
//                String description = data[6];

                    // Add the data directly to the table model
                    model.addRow(new Object[]{
                        itemNo,
                        itemName,
                        totalQty,
                        inProgress,
                        available, //                    reason,
                    //                    description
                    });
                }
            }
        } catch (IOException e) {
            System.err.println("Error reading inventory.txt: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Error loading data from inventory.txt", "Error", JOptionPane.ERROR_MESSAGE);
        }

//       model.setRowCount(0); // Clear the table before populating it
//    Map<String, String[]> stockData = loadStockData(); // Load stock data into a map
//    List<Item> items = new Item().itemList(); // Load item list from Item.txt
//
//    if (items != null && !items.isEmpty()) {
//        for (Item entry : items) {
//            String itemNo = entry.getItemNo();
//            String itemName = entry.getItemName();
//            String totalQty = "N/A", inProgress = "N/A", available = "N/A";
//
//            // Match itemNo with stock data
//            if (stockData.containsKey(itemNo)) {
//                String[] stockDetails = stockData.get(itemNo);
//                totalQty = stockDetails[0];
//                inProgress = stockDetails[1];
//                available = stockDetails[2];
//            }
//
//            // Print for debugging
//            System.out.println("Adding to table: " + itemNo + ", " + itemName);
//
//            // Add combined data to the table
//            model.addRow(new Object[]{
//                itemNo,
//                itemName,
//                totalQty,
//                inProgress,
//                available
//            });
//        }
//    } else {
//        System.err.println("No data available in Item.txt.");
//        JOptionPane.showMessageDialog(this, "There is no data in Item.txt", "No Data", JOptionPane.WARNING_MESSAGE);
//    }
//}
//
//// Helper method to load stock data from another file (e.g., Stock.txt)
//private Map<String, String[]> loadStockData() {
//    Map<String, String[]> stockMap = new HashMap<>();
//    String line;
//
//    try (BufferedReader br = new BufferedReader(new FileReader(INVENTORY_FILENAME))) {
//        while ((line = br.readLine()) != null) {
//            String[] data = line.split(", "); // Assuming data is comma-separated
//            if (data.length >= 4) { // Ensure the file has the required columns
//                String itemNo = data[0];
//                String totalQty = data[1];
//                String inProgress = data[2];
//                String available = data[3];
//                stockMap.put(itemNo, new String[]{totalQty, inProgress, available});
//            }
//        }
//    } catch (IOException e) {
//        System.err.println("Error reading Stock.txt: " + e.getMessage());
//    }
//
//    return stockMap;
//       
//       
//       
//       model.setRowCount(0); // Clear the table before loading new data
//    List<String> stockData = new ArrayList<>();
//    
//    try (BufferedReader br = new BufferedReader(new FileReader(INVENTORY_FILENAME))) {
//        String line;
//        while ((line = br.readLine()) != null) {
//            String[] data = line.split(", ");
//            if (data.length >= 7) { // Ensure all columns are available in the file
//                // Populate table with updated stock data
//                model.addRow(new Object[]{
//                    data[0], // Item No
//                    data[1], // Item Name
//                    data[2], // Total Quantity
//                    data[3], // Items In Progress
//                    data[4], // Available Items
//                    data[5], // Reason
//                    data[6]  // Description
//                });
//            }
//        }
//    } catch (IOException e) {
//        JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage());
//        e.printStackTrace();
//    }
//        List<Item> items = new Item().itemList();
//
//        if (items != null && !items.isEmpty()) {
//            for (Item entry : items) {
//                model.addRow(new Object[]{
//                    entry.getItemNo(),
//                    entry.getItemName(),
//                    entry.getItemPrice(),
//                    entry.getSupplierID(),
//                    entry.getItemStatus()
//                });
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "There is no data in Item.txt");
//        }
    }

    private void clearFormFields() {
        jTextField3.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox2.setSelectedIndex(0);
        jTextField5.setText("");
        jSpinner1.setValue(0);

    }
}
